### PR TITLE
Feature build html

### PR DESCRIPTION
**Pull request by thaomonster**
### What is the change? 
Add html and css styling.
### What does it fix? 
N/A
### Is this a fix or a feature?  
Feature
### Where should the reviewer start? 
Line 1 in HTML
Line 12 in CSS
### How should this be tested? 
open index.html

### CODE REVIEW

**Review by okalimbet — APPROVED** [review]
Really good organization! Love that you added lang to HTML tag, a nice detail.  Good use of different tags to separate sections of code

**Review by okalimbet — APPROVED** [review]
I like that you keep color choices in the beginning for right now. It will be useful till we finish the project. Also, nice use of percentages. Maybe we can change em later to vh, and adjust whitespaces on the left.

**Review by okalimbet — APPROVED** [review]

**Review by okalimbet — APPROVED** [review]
Good name changes, it makes them more clear. I think it's great we use vh now so the elements can shrink according to the screen size.

**Review by BearFrowns — APPROVED** [review]
Going along with Olga's reviews, everything looks great! Your HTML is very clean and well spaced (THANK YOU). I like that you made the change from Radio to individual Buttons. In the CSS, I also appreciate you working on making everything a percentage or vh - working with as few units as possible will make everything so much easier going forward. 
Awesome work and no conflicts! Approving and merging these changes now.

**Pull request merged**
