### PR TITLE
Feature form functionality II

### PR DESCRIPTION
**Pull request by BearFrowns**
### What does this PR do? 
Complete functionality of iteration 2:
-Activity Category border & icon colors now change
-Input fields (2) for time only accept numbers
-Start Activity button updates data model
-On click, Start Activity button will hide form and show timer
-Error messages added to inputs
### What is the change?
Refactoring of variables and functions as well as full functionality of iteration 2
### What does it fix?
n/a
### Is this a feature or a fix?
Complete Feature
### Where should the reviewer start? 
line 1: main.js      (lots of refactoring)
line 77: index.html
line 3: activity.js
line 41: styles.css
### How should this be tested? 
1. Open index.html
2. Select each category by their button (check color change)
3. Type input in accomplish field
4. Type two inputs (i.e. 09) into minutes field
5. Type two inputs into seconds field
6. Click "Start Activity"
7. Form should hide, timer should appear with your input times and color matching the previously selected category
---8. Refresh page---
9. Leave activity input field blank, enter time correctly, click "Start Activity" - error message below input field should appear
10. Input incorrect time in one field at a time, click "Start Activity - error message alert should appear

### CODE REVIEW

**Review by thaomonster — APPROVED** [review]
Everything looks good!

**Review by okalimbet — APPROVED** [review]
I like the names you gave to images, very descriptive and easy to understand. That's an interesting way to change colors for buttons using CSS!

**Review by thaomonster — APPROVED** [review]
I like the renames in the HTML.

**Review by thaomonster — APPROVED** [review]
Refactoring looks great! Thanks for all the hard work!

**Review by okalimbet — APPROVED** [review]
Good organized functions that are only responsible for one action. We need to look at displayUserInput() function later to try to refactor it, maybe there is an easier way to consider all these cases. I think it's good we moved images from global to a function  switchCategoryBtnImg(), it seems like we are using them only once.

**Pull request merged**
